# Generated by Django 4.0 on 2021-12-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('startTime', models.TimeField(auto_now_add=True)),
                ('endTime', models.TimeField(null=True)),
                ('complit', models.BooleanField(default=False)),
            ],
        ),
    ]
