# Generated by Django 4.0 on 2021-12-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_prod_endtime_alter_prod_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod',
            name='endTime',
        ),
    ]
